services:
  - type: web
    name: AttackMyApp
    env: dotnet
    plan: free
    repo: https://github.com/Igte312/AttackMyApp_API
    branch: master
    buildCommand: "dotnet publish -c Release"
    startCommand: "dotnet /app/AttackMyApp.dll"  # Comando para ejecutar tu aplicación
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
     