services:
  - type: web
    name: AttackMyApp
    env: docker
    plan: free
    repo: https://github.com/Igte312/AttackMyApp_API
    branch: master
    dockerfilePath: ./AttackMyApp/Dockerfile  # Ajusta esta ruta si el Dockerfile está en una subcarpeta
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
     